### ISSUE TITLE
A sequence of problems when wrapping an existing App

### ISSUE THREAD

**Issue by bompi88** [sircharleswatson/Electrometeor#15]
I had a typical Meteor app I wanted to set up using Electron (Electrometeor). The first problem I faced was with simple-schema, where I got the following error:

```
Exception in template helper: TypeError: S is not a function
    at inflectedLabel (http://localhost:3000/packages/aldeed_simple-schema.js?e210968641793751997ffe233af33b53af8566e4:2136:10)
    at SimpleSchema.getDefinition (http://localhost:3000/packages/aldeed_simple-schema.js?e210968641793751997ffe233af33b53af8566e4:2688:30)
    at SimpleSchema.label (http://localhost:3000/packages/aldeed_simple-schema.js?e210968641793751997ffe233af33b53af8566e4:2741:18)
    at Object.autoFormFieldLabelText (http://localhost:3000/packages/aldeed_autoform.js?b2b90d28d5cc29be68358bb3c8bb8a337992a7dd:1309:23)
    at http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2880:16
    at http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1651:16
    at http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2928:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12)
    at http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2927:27
    at Spacebars.call (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:172:18)
```

In response to this I forked `Simple-Schema` and did some "hacky" changes (https://github.com/aldeed/meteor-simple-schema/issues/317) to make sure it kind of worked in development mode, and added `string.js` to `package.json`. This only worked in dev-mode though, but that was the most important thing at the time. 

I was using Mac OSX 10.10.3, Node v0.10.36 and Meteor 1.1.0.2. All packages were up to date. I'll walk through the errors I have been encountered, so hopefully others can avoid having to go through the same thing I did.

When I first ran the `script/dist.js` script I got an App in the output dir `dist`, but when I tried to open it, nothing happened. Electron did start, but no window was opened. This is the output I got when running the dist-version from the command line:

```
/Users/xxx/projects/grand-view/dist/osx/GrandView.app/Contents/Resources/app
Starting production server
MongoPort:  51046
WebPort:  51045
2015-06-26T12:21:40.269+0200 [initandlisten] MongoDB starting : pid=29546 port=51046 dbpath=/Users/xxx/Library/Application Support/GrandView/data 64-bit host=dhcp-017012.wlan.ntnu.no
2015-06-26T12:21:40.269+0200 [initandlisten] db version v2.6.9
2015-06-26T12:21:40.269+0200 [initandlisten] git version: df313bc75aa94d192330cb92756fc486ea604e64
2015-06-26T12:21:40.269+0200 [initandlisten] build info: Darwin mci-osx108-2.build.10gen.cc 12.3.0 Darwin Kernel Version 12.3.0: Sun Jan  6 22:37:10 PST 2013; root:xnu-2050.22.13~1/RELEASE_X86_64 x86_64 BOOST_LIB_VERSION=1_49
2015-06-26T12:21:40.269+0200 [initandlisten] allocator: system
2015-06-26T12:21:40.269+0200 [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 51046, unixDomainSocket: { pathPrefix: "/Users/xxx/Library/Application Support/GrandView/data" } }, storage: { dbPath: "/Users/xxx/Library/Application Support/GrandView/data", smallFiles: true } }

Starting node child...
2015-06-26T12:21:40.269+0200 [initandlisten] exception in initAndListen: 10310 Unable to lock file: /Users/xxx/Library/Application Support/GrandView/data/mongod.lock. Is a mongod instance already running?, terminating
2015-06-26T12:21:40.269+0200 [initandlisten] dbexit:
2015-06-26T12:21:40.269+0200 [initandlisten] shutdown: going to close listening sockets...
2015-06-26T12:21:40.269+0200 [initandlisten] shutdown: going to flush diaglog...
2015-06-26T12:21:40.269+0200 [initandlisten] shutdown: going to close sockets...
2015-06-26T12:21:40.269+0200 [initandlisten] shutdown: waiting for fs preallocator...
2015-06-26T12:21:40.269+0200 [initandlisten] shutdown: lock for final commit...
2015-06-26T12:21:40.269+0200 [initandlisten] shutdown: final commit...
2015-06-26T12:21:40.269+0200 [initandlisten] shutdown: closing all files...
2015-06-26T12:21:40.269+0200 [initandlisten] closeAllFiles() finished
2015-06-26T12:21:40.269+0200 [initandlisten] dbexit: really exiting now

stderr:

stderr:  /Users/xxx/projects/grand-view/dist/osx/GrandView.app/Contents/Resources/app/bundle/programs/server/node_modules/fibers/future.js:278
						throw(ex);
						      ^

stderr:  Error: failed to connect to [localhost:51046]
    at Object.Future.wait (/Users/xxx/projects/grand-view/dist/osx/GrandView.app/Contents/Resources/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:98:1)
    at packages/accounts-base/accounts_common.js:141:1
    at /Users/xxx/projects/grand-view/dist/osx/GrandView.app/Contents/Resources/app/bundle/programs/server/packages/accounts-base.js:243:4
    at /Users/xxx/projects/grand-view/dist/osx/GrandView.app/Contents/Resources/app/bundle/programs/server/packages/accounts-base.js:1659:3
    at /Users/xxx/projects/grand-view/dist/osx/GrandView.app/Contents/Resources/app/bundle/programs/server/boot.js:222:10
    - - - - -
```

This was happening because a `mongodb` instance probably got instantiated and never terminated. So I did close the currently running `mongod` process, by:

``` sh
kill $(ps aux | grep '[m]ongod' | awk '{print $2}')
```

After this, no error occured when starting the app, but still no window got opened. I had to remove part by part of the app, to see what triggered this behaviour. I removed all what so ever, and it was still not working. After hours of debugging, I found out that you actually had to write "Meteor app started." to the server console at startup, and a main template had to be defined in the top root folder (`meteor`folder).

This is important, `index.js` actually checks for that exact printout:

``` js
if (Meteor.isServer) {
  Meteor.startup(function () {
    console.log('Meteor app started.');
  });
}
```

This is not actually an issue anymore, but more a log for those who encounter similar problems.

**Comment by sircharleswatson** [comment]
Thanks for that @bompi88 .

I ran into similar issues during development of this. I am not totally sure the reason why It needs to console.log a message in `Meteor.startup` but that was the only way it would work. I think it has something to do with electron waiting for it's subprocess (the meteor app) to start.

A lot of this code, I took from another similar project but that only worked on Mac.

**Comment by bompi88** [comment]
Yeah, I think that's the case, so the window opens when the server is ready. I really like this Electron-Meteor combo. You have done some great work here, @sircharleswatson. 

Should it be added to the README.md file maybe, that it is neecessary to keep that code snippet for it to work?

**Comment by sircharleswatson** [comment]
@bompi88 Yes, I will make a note about that, especially for people converting existing apps.

btw, I'd love to see what you're working on if possible.

**Comment by bompi88** [comment]
I will most likely finish late this summer. I can send you a message when that time arrives.

**Comment by sircharleswatson** [comment]
@bompi88 That'd be great! I look forward to it.

**Comment by bompi88** [comment]
Hi @sircharleswatson, I actually ran into a problem when distributing to the Windows platform. For some weird reason I can't start the app the regular way, I have to either run it from the commandline or create a bat-file that fires it up. Do you think this could happen because the app do not register the "Meteor app started." output? Maybe this is a Electron issue, for all I know, but it's probably something I did wrong among all those steps of trial and error.

**Comment by bompi88** [comment]
Have you looked into using electron-packager (https://github.com/maxogden/electron-packager) and electron-builder (https://github.com/loopline-systems/electron-builder) ?

**Comment by bompi88** [comment]
Ok, I borrowed a Windows computer now and tested it once more. The app actually runs the very first time you run it, but that is it. Then I have to run it using a bat-file.

**Comment by bompi88** [comment]
This happened to be solved by the same technique as in #11.

**Comment by sircharleswatson** [comment]
I'm going to re-open this issue so I remember to go through and document/fix some of these things.
