### ISSUE TITLE
Error running Windows App after building

### ISSUE THREAD

**Issue by RSchwan** [sircharleswatson/Electrometeor#24]
When I run my test app no window appears.
I'm running it on Windows 7 64 bit in VirtualBox.
Here my output:
```
[5268:0830/201240:INFO:CONSOLE(0)] Starting production
server

[5268:0830/201240:INFO:CONSOLE(0)] MongoPort:  51902
[5268:0830/201240:INFO:CONSOLE(0)] WebPort:  51901
[5268:0830/201240:INFO:CONSOLE(0)] 2015-08-30T20:12:40.481+0200 [initandlisten] MongoDB starting : pid=5484 port=51902 d
bpath=\Users\Developer\AppData\Local\Electrometeor\data 64-bit host=Virtual-PC
2015-08-30T20:12:40.497+0200 [initandlisten] targetMinOS: Windows 7/Windows Server 2008 R2
2015-08-30T20:12:40.497+0200 [initandlisten] db version v2.6.9
2015-08-30T20:12:40.497+0200 [initandlisten] git version: df313bc75aa94d192330cb92756fc486ea604e64
2015-08-30T20:12:40.497+0200 [initandlisten] build info: windows sys.getwindowsversion(major=6, minor=1, build=7601, pla
tform=2, service_pack='Service Pack 1') BOOST_LIB_VERSION=1_49
2015-08-30T20:12:40.497+0200 [initandlisten] allocator: system
2015-08-30T20:12:40.497+0200 [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 51902 }, storage: { dbPath: "\
Users\Developer\AppData\Local\Electrometeor\data", smallFiles: true } }

[5268:0830/201240:INFO:CONSOLE(0)] Starting node child...
[5268:0830/201240:INFO:CONSOLE(0)] 2015-08-30T20:12:40.497+0200 [initandlisten] journal dir=\Users\Developer\AppData\Local\
Electrometeor\data\journal
2015-08-30T20:12:40.497+0200 [initandlisten] recover : no journal files present, no recovery needed

[5268:0830/201240:INFO:CONSOLE(0)] 2015-08-30T20:12:40.622+0200 [initandlisten] allocating new ns file \Users\Developer\App
Data\Local\Electrometeor\data\local.ns, filling with zeroes...

[5268:0830/201240:INFO:CONSOLE(0)] 2015-08-30T20:12:40.809+0200 [FileAllocator] allocating new datafile \Users\Developer\Ap
pData\Local\Electrometeor\data\local.0, filling with zeroes...
2015-08-30T20:12:40.809+0200 [FileAllocator] creating directory \Users\Developer\AppData\Local\Electrometeor\data\_tmp

[5268:0830/201240:INFO:CONSOLE(0)] stderr:
C:\Users\Developer\Desktop\Electrometeor\dist\windows\Electrometeor\resources\app\bundle\programs\server\node_modules\fiber
s\fibers.js:16
        throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
              ^
Error: `C:\Users\Developer\Desktop\Electrometeor\dist\windows\Electrometeor\resources\app\bundle\programs\server\node_modul
es\fibers\bin\win32-ia32-v8-3.14\fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (C:\Users\Developer\Desktop\Electrometeor\dist\windows\Electrometeor\resources\app\bundle\program
s\server\node_modules\fibers\fibers.js:16:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Developer\Desktop\Electrometeor\dist\windows\Electrometeor\resources\app\bundle\program
s\server\boot.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

[5268:0830/201240:INFO:CONSOLE(0)] 2015-08-30T20:12:40.825+0200 [FileAllocator] done allocating datafile \Users\Developer\A
ppData\Local\Electrometeor\data\local.0, size: 16MB,  took 0.011 secs
2015-08-30T20:12:40.825+0200 [initandlisten] build index on: local.startup_log properties: { v: 1, key: { _id: 1 }, name
: "_id_", ns: "local.startup_log" }
2015-08-30T20:12:40.825+0200 [initandlisten]     added index to empty collection
2015-08-30T20:12:40.825+0200 [initandlisten] command local.$cmd command: create { create: "startup_log", size: 10485760,
 capped: true } ntoreturn:1 keyUpdates:0 numYields:0  reslen:37 194ms
2015-08-30T20:12:40.825+0200 [initandlisten] waiting for connections on port 51902

[7052:0830/201240:ERROR:gl_surface_egl.cc(173)] eglInitialize failed with error UNKNOWN
[7052:0830/201240:ERROR:gl_surface_win.cc(152)] GLSurfaceEGL::InitializeOneOff failed.
[7052:0830/201240:ERROR:gpu_child_thread.cc(163)] Exiting GPU process due to errors during initialization
[5268:0830/201340:INFO:CONSOLE(0)] 2015-08-30T20:13:40.778+0200 [clientcursormon] mem (MB) res:37 virt:203
2015-08-30T20:13:40.778+0200 [clientcursormon]  mapped (incl journal view):64
2015-08-30T20:13:40.778+0200 [clientcursormon]  connections:0
```

**Comment by sircharleswatson** [comment]
It looks like you didn't do the electron rebuild command after running the setup script

**Comment by RSchwan** [comment]
When I run electron-rebuild I get following error:
`Unable to find electron-prebuilt's version number, either install it or specify an explicit version`

**Comment by sircharleswatson** [comment]
Make sure to give it a version number with the rebuild command. 

electron-rebuild -v 0.30.4

**Comment by sircharleswatson** [comment]
@RSchwan Sorry about all the confusion. I'm currently working on making this much easier to use so hang tight! 

I thought I had changed the docs to specify that a version number is needed but it looks like I never actually did that. I'll do that asap so no one else misses it. That step is kinda hidden.

**Comment by RSchwan** [comment]
When I run `electron-rebuild -v 0.30.4`, I get a new error:
```
...
C:\Users\Developer\Desktop\Electrometeor\node_modules\electron-rebuild\lib\headers\.node-gyp\0.30.4\deps\v8\include\v8.h(33
58): fatal error C1003: error count exceeds 100; stopping compilation [C:\Users\Developer\Desktop\Electrometeor\node_module
s\electron-rebuild\node_modules\nslog\build\nslog.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Developer\Desktop\Electrometeor\node_modules\electron-rebuild\node_modu
les\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\Developer\\Desktop\\Electrometeor\\node_modules\\electron-rebuild\\node_modules\\npm\\n
ode_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Developer\Desktop\Electrometeor\node_modules\electron-rebuild\node_modules\nslog
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\Developer\\Desktop\\Electrometeor\\node_modules\\electron-rebuild\\node_modules\\npm\\bin\
\npm-cli.js" "rebuild" "--target=0.30.4" "--arch=x64"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.0
npm ERR! code ELIFECYCLE
npm ERR! nslog@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Developer\Desktop\Electrometeor\node_modules\npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (C:\Users\Developer\Desktop\Electrometeor\node_modules\electron-rebuild\lib\spawn.js:53:26)

    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

**Comment by sircharleswatson** [comment]
Makin progress haha. 

If I remember correctly, that error is due to not having the right prerequisites. Installing Visual Studio Express should solve that one. There is a link to the download in the README.

**Comment by RSchwan** [comment]
I have all the prerequisites (also Visual Studio Express) installed.

**Comment by sircharleswatson** [comment]
Hmm. I'd try looking up that msbuild error. I know I had to do that when I ran into that issue. I can't remember how to fix it though.

**Comment by RSchwan** [comment]
I had Visual Studio Express 2012 (link in README) installed. After I uninstalled Visual Studio Express 2012 and installed Visual Studio Express 2013, I could run `electron-rebuild -v 0.30.4` without problems.
Maybe you should update the link in the README.

But now I have a other problem. When I run `node ./script/dist.js` with node version 0.10.36 it just says `Starting Distribution Script...` and then the script stops leaving a bundle folder behind.

**Comment by sircharleswatson** [comment]
@RSchwan I can take a look at that tonight and let you know. That happens to me occasionally as well
